# Generated by Django 4.1.7 on 2023-02-16 16:23

import core.serializers
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('year', models.IntegerField()),
                ('publisher', models.CharField(max_length=128)),
                ('writers', models.CharField(max_length=256)),
                ('specialized_field', models.IntegerField(choices=[(0, 'گردشگری'), (1, 'توسعه'), (2, 'تجارت')], default=0)),
                ('book_type', models.IntegerField(choices=[(0, 'تألیف'), (1, 'ترجمه')], default=0)),
                ('research_group', multiselectfield.db.fields.MultiSelectField(choices=[('jg', 'جامعه شناسی گردشگری'), ('eg', 'اقتصاد گردشگری'), ('mb', 'مدیریت و برنامه\u200cریزی گردشگری'), ('tp', 'توسعه پایدار شهری-منطقه\u200cای'), ('mk', 'مرکز خدمات تخصصی')], max_length=3)),
                ('ISBN', models.CharField(max_length=15, null=True)),
                ('file', models.FileField(upload_to='')),
            ],
            bases=(models.Model, core.serializers.Dictable),
        ),
    ]
